#!/usr/bin/env bash
# Returns information about a subdomain given the subdomain and domain

subdomain_details () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
	subdomain_details "$2.$1" "$2"
else
	subdomain_details "www.$1" "www"
	subdomain_details "lb-01.$1" "lb-01"
	subdomain_details "web-01.$1" "web-01"
	subdomain_details "web-02.$1" "web-02"
fi
