#!/usr/bin/env bash
# This script installs Nginx on an ubunt server
# Nginx should listen to port 80
# Returns a page that contains 'Hello World!'...
# ...when querying Nginx at its root with a GET request
# systemctl can't be used to restart nginx

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
