#!/usr/bin/env bash
# This script installs nginx on a remote server
# Nginx is listening on port 80
# Nginx returns a page that contains the string 'hello world' when queried at its root

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/listen 80 default_server/a rewrite ^/tredirect_me http://www.youtube.com/watch?v=JCxGxK3GZiA permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default 
service nginx reload
