#!/usr/bin/env bash
# This script configures web-02 server as web-01

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i "40i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a rewrite ^/redirect_me http://www.youtube.com/watch?v=JCxGxK3GZiA permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
