#!/usr/bin/env bash
# configures server2 like server1

sudo apt-get update -y
sudo apt-get install -y nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx

# allows nginx to serve on http
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "47i $line" /etc/nginx/sites-available/default
sudo sed -i "22i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
# 404 Error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sed -i '48i\\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
