#!/usr/bin/env bash

# This script configures an nginx server to listen on
# port 80 of all the server's active IPv4 IPs

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
