#!/usr/bin/env bash
# This script configures an nginx server to listen on
# port 80 of all the server's active IPv4 IPs

cd /etc/nginx/sites-enabled/ || exit;
sudo rm default;
sudo ln -s /etc/nginx/sites-available/default default;
sudo service nginx restart
