#!/usr/bin/env bash
# Makes nginx listen on port 80 of all server ipv4
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
