#!/usr/bin/env bash
# This script makes nginx listen on port 80 for all server IP

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx restart
pkill -o nginx
