#!/usr/bin/env bash
# This script combines loop with condition

num=0

while [ $num -lt 10 ]
do
	if [ $num -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
		num=$(( num+1 ))
	else
		echo "Best School"
		num=$(( num+1 ))
	fi
done
