#!/usr/bin/env bash
# This script uses if condition to display some text

num=1

while [ $num -le 10 ]
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
		num=$(( num+1 ))
	elif [ $num -eq 8 ]
	then
		echo "good luck"
		num=$(( num+1 ))
	else
		echo "Best School"
		num=$(( num+1 ))
	fi
done

