#!/usr/bin/env bash
#This script configures an Ubuntu server with the following requirements:
#	resolves localhost to 127.0.0.1
#	resolves facebook.com to 8.8.8.8

cp /etc/hosts new_host
sed -i s/^127.*/"127.0.0.2	localhost"/ new_host
echo "8.8.8.8	facebook.com" >> new_host
cp new_host /etc/hosts
