#!/usr/bin/env bash
# This script makes sure that Nginx is running as the nginx user
# nginx is listening on all active IPs on port 8080
# apt-get should not be used

pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/\
	default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0644 /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
