#!/usr/bin/env bash
# Configures SSH client to use given private key
# Configures to refuse to authenticate using password
Host 34.203.75.235
	IdentitiesOnly yes
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
